apiVersion: apps/v1
kind: Deployment
metadata:
  name: midbuggy-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: midbuggy
  template:
    metadata:
      labels:
        app: midbuggy
    spec:
      containers:
      - name: mid
        image: 787939039510.dkr.ecr.us-west-2.amazonaws.com/mid
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
# service type loadbalancer       
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: midbuggy
    k8s-app: midbuggy
  name: midbuggy
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8080
  type: LoadBalancer
  selector:
    app: midbuggy
